# fly.toml - Discord Bot Configuration
app = "your-discord-bot-name"  # CHANGE THIS to your desired app name
primary_region = "syd"  # Sydney (closest to Auckland, NZ)

# Kill signal and timeout (important for bots)
kill_signal = "SIGINT"
kill_timeout = "5s"

# Build configuration
[build]

# Environment variables (non-sensitive only)
[env]
  PYTHONUNBUFFERED = "1"  # See Python logs in real-time

# VM configuration (free tier)
[vm]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

# Process configuration
[processes]
  app = "python main.py"

# Restart policy (important for bots)
[restart]
  policy = "always"  # Auto-restart if bot crashes

# Health check configuration
[[services]]
  internal_port = 8080  # Your bot's health server port
  protocol = "tcp"
  auto_stop_machines = false  # Keep bot running always
  auto_start_machines = true

  # HTTP service on port 80 (optional, for external checks)
  [[services.ports]]
    port = 80
    handlers = ["http"]

  # Health check that monitors your bot
  [[services.http_checks]]
    interval = "30s"        # Check every 30 seconds
    timeout = "5s"          # Fail if no response in 5 seconds
    grace_period = "30s"    # Wait 30s after start before checking
    method = "GET"
    path = "/"              # Your health_check endpoint

# Persistent volume configuration
[[mounts]]
  source = "bot_data"          # Volume name
  destination = "/data"        # Mount point inside container
  initial_size = "1GB"         # Volume size (1GB for free tier)